language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anshup7/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true anshup7/docker-react npm run test -- --coverage
